### ISSUE TITLE
Issue with monitor execution

### ISSUE THREAD

**Issue by Mokita-J** [mojtaba-eshghie/HighGuard#126]
### Description
Hi! I tried running HighGuard but encountered an issue while running the server and the Standalone CLI Monitor.

### Steps to reproduce this issue
1. `npm install` in main directory, `server/monitor` and `client`.
2. `npm start` in server or `node server/monitor/monitorCLI.js` in main directory.

### Behaviour:
```
Error: Cannot find module './utils/dcr-info'
Require stack:
- /HighGuard/server/monitor/setup.js
```
I tried replacing the [require argument](https://github.com/mojtaba-eshghie/HighGuard/blob/main/server/monitor/setup.js#L6) `drc-info` to `getDCRInfo`.
And after rerunning I get the following error:
```
Error: Cannot find module './utils/dbHandler.js'
Require stack:
- /HighGuard/server/monitor/setup.js
```

### Environment
Node v18.17.1
Npm 9.6.7

---

Could you give some tips on what I can do to solve this problem?
Thanks a lot :)

**Comment by mojtaba-eshghie** [comment]
Hi @Mokita-J 
Thanks for submitting the issue. We will update the installation instructions in the coming days; I will inform you once done.

**Comment by mojtaba-eshghie** [comment]
Hi @Mokita-J 
We have updated the installation instructions. Could you please try again to see how they work?

**Comment by Mokita-J** [comment]
Ack! Thanks for the update. I'll test it out and report back within a week :)

**Comment by Mokita-J** [comment]
Sorry for the late reply. I've successfully installed HighGuard and was able to run the CLI commands.
Thanks for the support!
